### ISSUE TITLE
Error filtering by plasmid genes.

### ISSUE THREAD

**Issue by Rachael-16** [Shamir-Lab/SCAPP#10]
Error introduced during plasmid filtering 
`File "/home/rachael/anaconda2/envs/scapp/bin/scapp", line 8, in <module>
    sys.exit(main())
  File "/home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/scapp.py", line 377, in main
    protfiles_path, None, ncbi_path, num_procs, PARAMS.GENE_MATCH_THRESH)
  File "/home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 164, in find_plasmid_gene_matches
    pf_blastpath = blast_protein_file(pf, dbpath, ncbi_bin, numthreads, outdir)
  File "/home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 110, in blast_protein_file
    subprocess.check_call(command, shell=True)
  File "/home/rachael/anaconda2/envs/scapp/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tblastn -db scapp/intermediate_files/hit_cycs/assembly_graph.cycs.fasta.blastdb -db_gencode 11 -query /home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/data/aa/aa1 -out scapp/intermediate_files/hit_cycs/aa1_blastdb.out -num_threads 4 -outfmt "6 qse`

output from blast.log

`Running command: tblastn -db scapp/intermediate_files/hit_cycs/assembly_graph.cycs.fasta.blastdb -db_gencode 11 -query /home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/data/aa/aa1 -out scapp/intermediate_files/hit_cycs/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"`

`Segmentation fault (core dumped)
Error running tblastn. Check paths to tblastn executable and input files.`

Generated blast results for nt1 fine. Using blast v 2.9.0  

I'm safe to assume this is a BLAST issue, overloading?

Thanks,

**Comment by dpellow** [comment]
It seems to be an issue with blastp. What happens if you just run the command by itself (the command after "Running command" in the blast log? What happens if you use an earlier version of BLAST?

**Comment by Rachael-16** [comment]
Hi dpellow, 

I have been trying to trouble shoot this issue myself and I actually think it the output format that is the issue. When I change the output format to just 6 and remove the "qseqid sseqid length pidint qlen slen evalue" 

It runs fine, no segmentation error. I edited it out of the find_plasmid_gene_matches.py file and ran again

This is error I got

``Traceback (most recent call last):
  File "/home/rachael/anaconda2/envs/scapp/bin/scapp", line 8, in <module>
    sys.exit(main())
  File "/home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/scapp.py", line 326, in main
    ncbi_path, num_procs, PARAMS.GENE_MATCH_THRESH)
  File "/home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 172, in find_plasmid_gene_matches
    get_blast_hits(pbr, hit_contigs_set, thresh)
  File "/home/rachael/anaconda2/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 126, in get_blast_hits
    matchlen = int(splt[2])

ValueError: invalid literal for int() with base 10: '72.292' ``

Can you interpret it? 

Is there an error with the formatting ?

**Comment by dpellow** [comment]
SCAPP parses and uses the output of BLAST and expects it in the format specified by SCAPP, if you change the format you will also need to change the parsing to match. However, that shouldn't be necessary to get this to run, and I recommend not to modify the code in this way.

The original error is probably am error in tblastn - What happens if you just run the command by itself (the command after "Running command" in the blast log? What happens if you use an earlier version of BLAST?

What code are you running separately?

What are the details of the compute cluster installation? Are you installing with conda? Are you sure you are using python3 (I believe numpy v1.17 dropped support for Python2)?

**Comment by dpellow** [comment]
I've pinned numpy release 1.17.4 specifically, which hopefully solves the last issue. Please re-open if it doesn't.
