### ISSUE TITLE
Reporting an Error

### ISSUE THREAD

**Issue by jotes35** [Shamir-Lab/SCAPP#11]
Hi @dpellow I would like to bring to your notice an error I encountered when using SCAPP. I installed SCAPP through anaconda using the yaml file. I run the programme and got an error. So I checked the blast_std.log which read
_No blast db provided, creating one
Running command: makeblastdb  -in /home/user/analysis/output/assembly/ARWA_IA/assembly_graph.fastg -dbtype nucl -out /home/user/analysis/output/plasmids/ARWA_IA/intermediate_files/assembly_graph.fastg.blastdb

Building a new DB, current time: 08/03/2020 01:43:55
New DB name:   /home/user/analysis/output/plasmids/ARWA_IA/intermediate_files/assembly_graph.fastg.blastdb
New DB title:  /home/user/analysis/output/assembly/ARWA_IA/assembly_graph.fastg
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: Function not implemented
Error creating blast database. Check path to makeblastdb executable._

I solved it by separately instaling blast which include the makeblastdb file and adding to $PATH and it worked.

**Comment by dpellow** [comment]
Yes, as explained in the readme, BLAST must be installed. You can add it to your PATH variable, or include the path in the config.json file. Installing SCAPP through bioconda will avoid having to install the prerequisites yourself.
