### ISSUE TITLE
tblastn error

### ISSUE THREAD

**Issue by jpaganini** [Shamir-Lab/SCAPP#12]
Hi guys, 

how are you? i hope everything is going fine! I'm having an issue running this tool. I installed SCAPP thru conda, and I get this output:

**Input Command**
`$ scapp -g input_fastg/GCA_010365325.1_ASM1036532v1.fastg -o GCA_010365325.1_ASM1036532v1 -r1 input_reads/GCA_010365325.1_ASM1036532v1_R1.fq -r2 input_reads/GCA_010365325.1_ASM1036532v1_R2.fq`

**Command line ouput**

Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Finding plasmid-specific genes with BLAST
Starting SCAPP plasmid finding
31.3877315 38.037443944192034 57.5134615
================== Added paths ====================
4 nodes remain in component
('EDGE_190373_length_154_cov_59.012987', 'EDGE_245952_length_1127_cov_24.620952', 'EDGE_136789_length_117_cov_67.450000', 'EDGE_250280_length_1215_cov_25.483304')
 
7 nodes remain in component
('EDGE_490763_length_79_cov_23.000000', "EDGE_246758_length_2085_cov_25.762948'", "EDGE_217413_length_103_cov_70.846154'", 'EDGE_242611_length_157_cov_58.912500', "EDGE_255018_length_203_cov_25.722222'", 'EDGE_60969_length_129_cov_48.634615')
 
18 nodes remain in component
16 nodes remain in component
("EDGE_250946_length_17843_cov_27.647754'", 'EDGE_102653_length_95_cov_59.000000', "EDGE_232675_length_79_cov_78.500000'", 'EDGE_251090_length_84_cov_101.142857', 'EDGE_251096_length_78_cov_76.000000', "EDGE_674293_length_79_cov_54.000000'")
 
('EDGE_251104_length_3907_cov_27.885379', "EDGE_617311_length_94_cov_51.941176'", "EDGE_250872_length_10000_cov_28.261614'", "EDGE_251090_length_84_cov_101.142857'", 'EDGE_232675_length_79_cov_78.500000', 'EDGE_251100_length_1892_cov_26.307989', 'EDGE_251090_length_84_cov_101.142857', 'EDGE_251096_length_78_cov_76.000000')
 
52 nodes remain in component
52 nodes remain in component
("EDGE_250036_length_2959_cov_26.595420'", "EDGE_274885_length_84_cov_69.571429'", "EDGE_105401_length_199_cov_31.573770'", "EDGE_29399_length_83_cov_68.833333'", "EDGE_230431_length_317_cov_31.395833'", 'EDGE_205349_length_112_cov_54.685714', 'EDGE_247410_length_2814_cov_26.903544', 'EDGE_248608_length_204_cov_27.244094', 'EDGE_93819_length_88_cov_63.818182', 'EDGE_219851_length_494_cov_32.594724', 'EDGE_239893_length_261_cov_28.065217', 'EDGE_196115_length_142_cov_57.553846', 'EDGE_255026_length_340_cov_23.931559', "EDGE_714417_length_101_cov_59.500000'", "EDGE_49137_length_100_cov_24.608696'", "EDGE_181755_length_97_cov_46.550000'")

[..... similar output..... ]
 
3010 nodes remain in component
3000 nodes remain in component
2964 nodes remain in component
2940 nodes remain in component
2888 nodes remain in component
2888 nodes remain in component
 
("EDGE_252572_length_39959_cov_26.194800'", "EDGE_94587_length_80_cov_45.666667'", "EDGE_2633_length_81_cov_103.250000'", "EDGE_248926_length_1886_cov_25.054726'", 'EDGE_400565_length_83_cov_49.166667', "EDGE_230269_length_79_cov_74.000000'", 'EDGE_2633_length_81_cov_103.250000', 'EDGE_94585_length_81_cov_53.500000')

 
Filtering plasmids by plasmid-specific genes
Error filtering by plasmid genes. Check BLAST output file (blast_std.log)
Traceback (most recent call last):
  File "/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/bin/scapp", line 10, in <module>
    sys.exit(main())
  File "/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/scapp.py", line 377, in main
    protfiles_path, None, ncbi_path, num_procs, PARAMS.GENE_MATCH_THRESH)
  File "/hpc/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 164, in find_plasmid_gene_matches
    pf_blastpath = blast_protein_file(pf, dbpath, ncbi_bin, numthreads, outdir)
  File "/hpc/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 110, in blast_protein_file
    subprocess.check_call(command, shell=True)
  File "/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tblastn -db GCA_010365325.1_ASM1036532v1/intermediate_files/hit_cycs/GCA_010365325.1_ASM1036532v1.cycs.fasta.blastdb -db_gencode 11 -query /home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/data/aa/aa2 -out GCA_010365325.1_ASM1036532v1/intermediate_files/hit_cycs/aa2_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"' died with <Signals.SIGSEGV: 11>.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
**I've checked the blast log. Info below**

No blast db provided, creating one
Running command: makeblastdb  -in input_fastg/GCA_010365325.1_ASM1036532v1.fastg -dbtype nucl -out GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb

Building a new DB, current time: 09/09/2020 14:44:54
New DB name:   /hpc/dla_mm/jpaganini/data/scapp_test/GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb
New DB title:  input_fastg/GCA_010365325.1_ASM1036532v1.fastg
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1422 sequences in 0.142929 seconds.
Running blast search for gene (nt) sequences in blast db
Running command: blastn -task megablast -db GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb -query /home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/data/nt/nt3 -out GCA_010365325.1_ASM1036532v1/intermediate_files/nt3_blastdb.out -num_threads 16 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Running command: blastn -task megablast -db GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb -query /home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/data/nt/nt1 -out GCA_010365325.1_ASM1036532v1/intermediate_files/nt1_blastdb.out -num_threads 16 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Running command: blastn -task megablast -db GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb -query /home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/data/nt/nt2 -out GCA_010365325.1_ASM1036532v1/intermediate_files/nt2_blastdb.out -num_threads 16 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Running blast search for protein (aa) sequences in blast db
Running command: tblastn -db GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb -db_gencode 11 -query /home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/data/aa/aa1 -out GCA_010365325.1_ASM1036532v1/intermediate_files/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Error running tblastn. Check paths to tblastn executable and input files.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
**tblastn seems to be the problem. However, this tool executes with no problem within the environment that I created for SCAPP, even using the same files. Just in case, I also added the tblastn to the PATH variable, but the error keeps on replicating.**

`$ echo $PATH`
/opt/sge/bin:/opt/sge/bin/lx-amd64:/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/bin:/home/dla_mm/jpaganini/data/miniconda3/condabin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/hpc/local/CentOS7/dla_mm/bin:/hpc/local/CentOS7/dla_mm/sbin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/gnu/profiles/base/bin:/home/dla_mm/jpaganini/bin:/home/dla_mm/jpaganini/data/piggy/bin:/gnu/profiles/base/bin:/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/bin/tblastn:/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/bin:/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/bin:/home/dla_mm/jpaganini/data/miniconda3/envs/scapp/bin/blastn

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

**Any idea of what might cause this issue? Thanks in advance for your help! cheers**

**Comment by dpellow** [comment]
Thanks for the interest and detailed bug report. It looks like this is an issue with tblastn.
Can you let me know what version of tblastn you are using (tblastn -h should show this information)?
Also, what happens if you run the exact command run by SCAPP:  
`tblastn -db GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb -db_gencode 11 -query /home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/data/aa/aa1 -out GCA_010365325.1_ASM1036532v1/intermediate_files/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"`

**Comment by jpaganini** [comment]
Hi! 

Thanks for your prompt reply! 

**tblastn version is 2.9.0**

`tblastn -h`

USAGE
  tblastn [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-qcov_hsp_perc float_value] [-max_hsps int_value]
    [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-db_gencode int_value] [-ungapped]
    [-max_intron_length length] [-seg SEG_options]
    [-soft_masking soft_masking] [-matrix matrix_name]
    [-threshold float_value] [-culling_limit int_value]
    [-best_hit_overhang float_value] [-best_hit_score_edge float_value]
    [-subject_besthit] [-window_size int_value] [-lcase_masking]
    [-query_loc range] [-parse_deflines] [-outfmt format] [-show_gis]
    [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-sorthits sort_hits]
    [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-remote] [-comp_based_stats compo]
    [-use_sw_tback] [-in_pssm psi_chkpt_file] [-version]

DESCRIPTION
   Protein Query-Translated Subject BLAST 2.9.0+

--------------------------------------------------------------------------

**I also runned the command as you mentioned, within the same conda environment in which I installed SCAPP and it works fine! It provides a perfect tblastn output, which was really surprising**

**Comment by dpellow** [comment]
OK, the error is a segmentation fault from BLAST, but it seems like it's not always reproduced when running tblastn.

To debug this I suggest trying the following steps and letting me know what the results are:

- run the tblastn command directly with a higher value of -num_threads to see if this reproduces the error.
- rerun SCAPP to see if the error is still reproduced (note you can use the -b option to run using the bam file that was created in previous runs instead of the read files to skip the alignment step and save time)
- rerun scapp with only one thread using option -p 1 (again re-use the already created bam file to save time)

**Comment by dpellow** [comment]
@jpaganini [this recent release note from NCBI](https://www.ncbi.nlm.nih.gov/sites/books/NBK131777/#_Blast_ReleaseNotes_BLAST_2_10_1_June_8_2_) reports a bug fix in tblastn multi-threading in BLAST 2.10.1.
Let me know if you are able to use that version and it fixes the problem. Otherwise, can let me know the results of the above actions and I can update SCAPP to shut of multi-threading for the tblastn stage if it seems like that will fix the problem.
Thanks!

**Comment by jpaganini** [comment]
Hi dpellow,

Thanks a lot for your quick answers!
Well... so I tried a few things:

**1) I run tblastn with a higher value of threads (16), and I got the segmentation error:**

**Input command**
`$ tblastn -db GCA_010365325.1_ASM1036532v1/intermediate_files/GCA_010365325.1_ASM1036532v1.fastg.blastdb -db_gencode 11 -query /home/dla_mm/jpaganini/data/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/data/aa/aa1 -out GCA_010365325.1_ASM1036532v1/intermediate_files/aa1_blastdb_16cores.out -num_threads 16 -outfmt "6 qseqid sseqid length pident qlen slen evalue" `

**Output**
Segmentation fault (core dumped)

------------------------------------------------------------------------------------------------------------------------------------------------------------
 **2) I tried running SCAPP with one thread by adding -p 1**
`$ scapp -g input_fastg/GCA_010365325.1_ASM1036532v1.fastg -o GCA_010365325.1_ASM1036532v1 -r1 input_reads/GCA_010365325.1_ASM1036532v1_R1.fq -r2 input_reads/GCA_010365325.1_ASM1036532v1_R2.fq -p 1`
***it works now***

-------------------------------------------------------------------------------------------------------------------------------------------------------------
**I  also tried to install the new version of blast using conda:**
`conda install -c bioconda blast=2.10.1`

**And re-run scapp with defaults threads**
`$ scapp -g input_fastg/GCA_010365325.1_ASM1036532v1.fastg -o GCA_010365325.1_ASM1036532v1 -r1 input_reads/GCA_010365325.1_ASM1036532v1_R1.fq -r2 input_reads/GCA_010365325.1_ASM1036532v1_R2.fq
`
**And it also works**

**Comment by dpellow** [comment]
OK thanks for that report! I think now that you have BLAST 2.10.1 with that bug fix for the multi-threading segmentation fault SCAPP should work. I will try out pinning that required version of BLAST in the bioconda recipe.

**Comment by dpellow** [comment]
The updated bioconda recipe with the necessary BLAST version pinned has been approved and merged. Installing from Bioconda should now ensure BLAST >=2.10.1 is installed.
