### ISSUE TITLE
BWA/samtools error

### ISSUE THREAD

**Issue by dpellow** [Shamir-Lab/SCAPP#15]
> Great! Hope you are able to use it to identify interesting plasmids. Let us know if you run into any other problems

(scapp-new) hsv709@pallas:/mibi/Wanli/benchmark$ scapp -g assembly-out/assembly_graph.fastg -k 99  -r1 R1.fq.gz -r2 R2.fq.gz -o scapp-out -p 20

Creating BAM file of read mappings with BWA
Traceback (most recent call last):
  File "/mibi/Wanli/anaconda/envs/scapp-new/bin/scapp", line 10, in <module>
    sys.exit(main())
  File "/mibi/Wanli/anaconda/envs/scapp-new/lib/python3.7/site-packages/scapp/scapp.py", line 234, in main
    subprocess.check_call(cmd,stderr=subprocess.STDOUT, stdout=bwa_outfile, shell=True)
  File "/mibi/Wanli/anaconda/envs/scapp-new/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bwa mem -t 20 scapp-out/intermediate_files/assembly_graph.nodes.fasta R1.fq.gz R2.fq.gz | samtools  view -buS -@ 19 - > scapp-out/intermediate_files/reads_pe.bam' returned non-zero exit status 1.

today, i run another data, but raise error again, like this.  the fastg file is output from spades, and the assembly k-mer are 21,33,55,77,99, so the k is scapp is 99.  before this, the assembler i used is megahit. so i don`t know whether this is the problem

_Originally posted by @aaa-meituo-aaa in https://github.com/Shamir-Lab/SCAPP/issues/14#issuecomment-706956523_

**Comment by dpellow** [comment]
I don't think the problem has to do with the assembler.

What are the contents of the file `scapp-out/logs/bwa_out.log`?

How did you install SCAPP, what version of SCAPP is it?

What versions of BWA and samtools do you have? (If you type BWA in the command line, the version will be listed at the top of the output. Same for samtools)
I see that a new version of samtools was just released, I'm checking the documentation for it now. Please let me know especially about your samtools version as the latest update was probably installed.
EDIT: I don't see anything in the release notes for samtools v1.11 that indicates a change that would not be compatible with SCAPP. Please let me know about the above questions. Thanks!

_Originally posted by @dpellow in https://github.com/Shamir-Lab/SCAPP/issues/14#issuecomment-706983910_

**Comment by aaa-meituo-aaa** [comment]
this is the conda list of the environment that i used. scapp=0.1.4, samtools=1.9 bwa = 0.7.17
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
blas                      2.17                   openblas    conda-forge
blast                     2.10.1          pl526he19e7b1_1    bioconda
bwa                       0.7.17               hed695b0_7    bioconda
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.11.0               h470a237_1    bioconda
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37he5f6b98_2    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
decorator                 4.4.2                      py_0    conda-forge
entrez-direct             13.9            pl526h375a9b1_0    bioconda
expat                     2.2.9                he1b5a44_2    conda-forge
joblib                    0.14.1             pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20191231         h46ee950_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblapacke                3.8.0               17_openblas    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_5    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
llvm-openmp               10.0.1               hc9558a2_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
numpy                     1.17.4           py37hd5be1e1_0    defaults
numpy-base                1.17.4           py37h2f8d375_0    defaults
openssl                   1.1.1h               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pip                       20.2.3                     py_0    conda-forge
plasclass                 0.1.0                      py_0    bioconda
pysam                     0.15.3           py37hda2845c_1    bioconda
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  h46ee950_1    conda-forge
samtools                  1.9                 h8571acd_11    bioconda
scapp                     0.1.4                      py_0    bioconda
scikit-learn              0.21.3           py37hcdab131_0    conda-forge
scipy                     1.3.2            py37h921218d_0    conda-forge
setuptools                49.6.0           py37he5f6b98_2    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge


and the log file:
[bwa_index] Pack FASTA... 0.44 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=58046044, availableWord=16083936
[BWTIncConstructFromPacked] 10 iterations done. 26530428 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 49010940 characters processed.
[bwt_gen] Finished constructing BWT in 25 iterations.
[bwa_index] 21.36 seconds elapse.
[bwa_index] Update BWT... 0.34 sec
[bwa_index] Pack forward-only FASTA... 0.24 sec
[bwa_index] Construct SA from BWT and Occ... 8.32 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index scapp-out/intermediate_files/assembly_graph.nodes.fasta
[main] Real time: 31.470 sec; CPU: 30.693 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 1333334 sequences (200000100 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (17, 230131, 169149, 22)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (231, 838, 4624)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 13410)
[M::mem_pestat] mean and std.dev: (2255.76, 2828.20)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 17803)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (273, 808, 2302)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 6360)
[M::mem_pestat] mean and std.dev: (1318.07, 1464.57)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 8389)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (377, 1106, 2959)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 8123)
[M::mem_pestat] mean and std.dev: (1805.75, 1948.87)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 10705)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (242, 731, 2382)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 6662)
[M::mem_pestat] mean and std.dev: (1500.81, 2002.43)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 9511)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 1333334 reads in 629.862 CPU sec, 252.289 real sec
[E::sam_parse1] query name too long
[W::sam_read1] Parse error at line 22265
[main_samview] truncated file.

**Comment by dpellow** [comment]
OK thanks did you install SCAPP from bioconda? I'm not sure why you got samtools v 1.9. Can you see if you run into the same problem with samtools v 1.10?

According to the log file one of the names is too long. Can you let me know what are the first lines of assembly_graph.fastg and and the read file (R1.fq) ?

**Comment by aaa-meituo-aaa** [comment]
yes, i install scapp by bioconda. 

reads name:
@SYN_0_24445_24594_23974_+_339279274_1_._NZ{CP029979.1$Escherichia$coli$strain$99-3165$plasmid$unnamed1&0_621_770_23974_-_339255450_1_._NZ{CP029979.1$Escherichia$coli$strain$99-3165$plasmid$unnamed1 1:
TGCTCCCGTTGTGATTCACGCAGCACACTCTCCGGCAGCGCGGCTTCCCGTTCAGTTATGTCAGCCCGGTCACGCTCCTGCCCGGCAATTTCCCTGACAGCCTGCTCTGTTTTACCATCCGGCAGGTCAGGTTTGTTCTCTGCCATTTTT
+
>8;99<?AA=>?BACCDCDEEBCDDBDDDC>ABEBCB=EBBA>BBCED>B@EAAEBD:AB@BACD@@@?A@CAAAAACD@<AE@?C?CDCCDBAECBEA??@>>AB@>CA@B=A>@B>=:@@CB>ECAAB;@@>;?<?A89;5:>75855

fastg file
![image](https://user-images.githubusercontent.com/58076352/95745131-1da04500-0cc7-11eb-8796-acef174efa09.png)

**Comment by aaa-meituo-aaa** [comment]
![image](https://user-images.githubusercontent.com/58076352/95745204-3ad51380-0cc7-11eb-8696-69e9f92d1eed.png)
reads 

is the reads header too long??

**Comment by aaa-meituo-aaa** [comment]
and i am trying using samtools=1.10

**Comment by dpellow** [comment]
> and i am trying using samtools=1.10

OK let me know if samtools v1.10 works better. It's strange that bioconda didn't install that automatically.

> is the reads header too long??

I think it might be, I haven't seen this problem before, but samtools may only be able to handle headers of a certain length? Is there a way to shorten the headers? I think usually the sequencer doesn't make such long names, do you know why they are so long?

**Comment by dpellow** [comment]
Also - are these reads from a sequencer or from a read simulator? Can you tell me which sequencer/simulator so that I can check if they limit read header length?

**Comment by aaa-meituo-aaa** [comment]
> > and i am trying using samtools=1.10
> 
> OK let me know if samtools v1.10 works better. It's strange that bioconda didn't install that automatically.
> 
> > is the reads header too long??
> 
> I think it might be, I haven't seen this problem before, but samtools may only be able to handle headers of a certain length? Is there a way to shorten the headers? I think usually the sequencer doesn't make such long names, do you know why they are so long?
> 
> Can you check how long the line that gives the error is? Try `zcat (or maybe gunzip) R1.fq.gz | sed -n '22264,22266p;22267q'`

samtools is not working, same error.

Creating BAM file of read mappings with BWA
Traceback (most recent call last):
  File "/mibi/Wanli/anaconda/envs/scapp-new/bin/scapp", line 10, in <module>
    sys.exit(main())
  File "/mibi/Wanli/anaconda/envs/scapp-new/lib/python3.7/site-packages/scapp/scapp.py", line 234, in main
    subprocess.check_call(cmd,stderr=subprocess.STDOUT, stdout=bwa_outfile, shell=True)
  File "/mibi/Wanli/anaconda/envs/scapp-new/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bwa mem -t 20 scapp-out/intermediate_files/assembly_graph.nodes.fasta R1.fq.gz R2.fq.gz | samtools  view -buS -@ 19 - > scapp-out/intermediate_files/reads_pe.bam' returned non-zero exit status 1.

**Comment by aaa-meituo-aaa** [comment]
> Can you tell me which sequencer/simulator so that I can check if they limit read header length?

yes,  the simulator is randomreads.sh

**Comment by aaa-meituo-aaa** [comment]
> > Can you tell me which sequencer/simulator so that I can check if they limit read header length?
> 
> yes, the simulator is randomreads.sh

![image](https://user-images.githubusercontent.com/58076352/95747186-9523a380-0cca-11eb-9bcd-a438ac6a5bb5.png)
maybe i should set a reads number, ?

**Comment by dpellow** [comment]
Interesting, I am not familiar with all the options of the simulator, but it is very strange that the default is not compatible with samtools.

I suggest trying both `illuminanames=t` (so that paired reads have the same name) and also `simplenames=t` (I'm not sure I understood correctly what this does, but it seems like it will shorten the read names by not using internal coordinates).

Note it seems that you can also set `prefix=<some string>` so that the reads will be named with that string as a prefix instead of with the longer names, but again, I'm not 100% sure of this)

**Comment by aaa-meituo-aaa** [comment]
> Interesting, I am not familiar with all the options of the simulator, but it is very strange that the default is not compatible with samtools.
> 
> I suggest trying both `illuminanames=t` (so that paired reads have the same name) and also `simplenames=t` (I'm not sure I understood correctly what this does, but it seems like it will shorten the read names by not using internal coordinates).
> 
> Note it seems that you can also set `prefix=<some string>` so that the reads will be named with that string as a prefix instead of with the longer names, but again, I'm not 100% sure of this)

ok, i will changing the header and see what will happend

**Comment by dpellow** [comment]
Great, thank you!
You could do a test with just a few reads and check the output of the simulator to see what the read headers are like.

**Comment by dpellow** [comment]
@aaa-meituo-aaa I've looked into the various options and apparently simply using `illuminanames=t` should be enough.

**Comment by dpellow** [comment]
@Wanli-HE did that work?

**Comment by dpellow** [comment]
Closing this issue - @Wanli-HE feel free to re-open if it has not been adequately addressed.

Summary of thread:
User attempted to use default SCAPP pipeline which uses BWA to align sample reads to assembled contigs. BWA has strict requirement on maximum length allowed for read name. User's reads were generated with randomreads.sh script from BBMap, which creates very long read names, incompatible with BWA.
Various options in the simulator create shorter read names (e.g. `illuminanames=t`).
