### ISSUE TITLE
No module named 'recyclelib'

### ISSUE THREAD

**Issue by pianpianyouche** [Shamir-Lab/SCAPP#2]
Hi,

I have installed this tool successfully. However, when I tried to invoke it with the following command, an error occurs. 

python scapp.py
Traceback (most recent call last):
File "scapp.py", line 12, in <module>
import recyclelib.utils as utils
ModuleNotFoundError: No module named 'recyclelib'

Any suggestions to solve this problem?
Thank you!

**Comment by pianpianyouche** [comment]
After reinstalled Recycler, problem solved.

**Comment by dpellow** [comment]
Thanks for your interest in using SCAPP and letting us know about this problem. I'm glad you were able to fix it.
Can you let us know some more information so we can see if there is anything we need fix:
- Did you install SCAPP in a virtual environment?
- What version of Python were you using?
- What command did you use to install SCAPP?

It is strange that installing Recycler solved the problem with SCAPP. What command did you use to install Recycler?
Thanks!
