### ISSUE TITLE
Is metaFlye being for long-read metagenome assembly create an issue for short reads?

### ISSUE THREAD

**Issue by ilkaybuysal** [Shamir-Lab/SCAPP#21]
metaFlye is a long-read metagenome assembler and SCAPP seems to be optimized for short-read sequences. I was wondering if this poses an issue?

**Comment by dpellow** [comment]
Yes SCAPP is developed for short, paired-end read metagenomic experiments. These can be assembled with metaSPAdes or MegaHit for example.
SCAPP may work on an assembly of long reads created by a different tool, but hasn't been developed or tested for that
