### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by dluecking** [Shamir-Lab/SCAPP#22]
Hi,

I'm trying to implement SCAPP in my workflow, however, I ran into the following error message when running SCAPP on a graph created by metaspades.
```
scapp -g crosbie_assembly_graph.fastg -o here -l 1000 -p 20
Traceback (most recent call last):
  File "/home/dlueckin/bin/miniconda3/envs/scapp/bin/scapp", line 8, in <module>
    sys.exit(main())
  File "/home/dlueckin/bin/miniconda3/envs/scapp/lib/python3.7/site-packages/scapp/scapp.py", line 232, in main
    samtools_file + "  view -buS -@ " + str(num_procs-1) + " - > " + reads_bam
TypeError: can only concatenate str (not "NoneType") to str
```

Any idea what could've gone wrong? 
Thanks
Dom

Additional information:
- SCAPP installed via conda (yml file)
- Linux linux-desktop-1 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux
- 124 GB RAM
- 40 Cores
- input graph: 7.1 GB
- assembler used: metaspades.py

**Comment by dpellow** [comment]
Yes you need to either provide a bam file of the alignments of the reads to the graph (using option `-b`) or the reads themselves that SCAPP will then align (using options `-r1` and `-r2` for the read files).
