### ISSUE TITLE
recovery of circular viral genome

### ISSUE THREAD

**Issue by hitig** [Shamir-Lab/SCAPP#23]
Dear colleague,
 Thanks for this code.
 Can SCAPP be used to recover circular viral genome? 
 SCAPP will search node against PSGs in which only file nt3 contained putative and replication genes of certain viruses, which can not represent all genes specific to viruses.  Does turn-off of plasmid specific genes use mean that SCAPP can recover circular viral genome? 
 But when I did so (-gh False), SCAPP ran almost normally, but always (3 tests) exited at the very end of running, i.e. getting into Transforming scores (It ran very smoothly when -gh was True ).

**Comment by dpellow** [comment]
Thanks for your interest in using SCAPP. It is designed specifically for assembling circular plasmids from metagenomic samples and not meant for viruses. 

It may be possible to try to assemble circular viral genomes by excluding all information about plasmids - specifically, both -gh and -sc flags should be false. Even more preferable would be to replace the sets of plasmid specific genes with your own sets of virus specific genes.

I didn't fully understand what the error that you are seeing is. What do you mean that it exited at the end? Did it run through the cycle finding steps? Was there an error message in any of the log files? If you can provide more details I will try to help determine what is the problem.

**Comment by hitig** [comment]
Hi David,
Thanks for your immediate response.
Yes, it abnormally existed at the end of running when -gh is False, the scapp.log ended with 'Transforming scores'. 

Anyway, I don't care about this abnormal exist. I have tested it with false -gh and -sc flags as you suggested, it ran normally, but did not generate  *.confident_cycs.fasta, I guess the *.confident_cycs.fasta was determined based on the plasmid score and PSG blast hit. 

Does the *.cycs.fasta in the directory of intermidiate_files contain all circular sequences? If so, can I use them for further identification of circular viral genomes?

**Comment by dpellow** [comment]
Yes the confident_cycs file is based on the genes and plasmid scores and won't be output without those. In the intermediate_files directory the cycs.fasta  file contains cycles in the assembly graph that pass certain tests (coverage, paired-end read matches) making it likely that they are from a single organism.

I guess you could test to check if any of them seem likely to be viral genomes although this is not what SCAPP is designed to be used for so there may be better ways to achieve the same goal.
