### ISSUE TITLE
Questions about metaflye_gfa2fastg.py

### ISSUE THREAD

**Issue by yusuketsuda** [Shamir-Lab/SCAPP#29]
Hello.
Thank you for developing this wonderful tool!!!

I converted a gfa file from metaFlye into a fastg file by your script "metaflye_gfa2fastg.py" and assembly the fastg file, but the following error always occurs.

`KeyError: "edge_6_len_44418_cov_21.0;>edge_6_len_44418_cov_21.0'"`

run_test.sh was worked without any trouble, so I checked "metaflye_gfa2fastg.py".

Proper edges are written as `>edge_(number)_len_(number)....` but the edge with erorr message is `edge_6_len_44418_cov_21.0;>edge_6_len_44418_cov_21.0`.
In the script "metaflye_gfa2fastg.py", line 55-56 is
```
     else:
          o.write('>'+name+"_len_"+str(fields[0])+"_cov_"+str(fields[1])+";") 
```

In my gfa file, the `pos_neighours` in edge_6 is 0, so `>edge_6_len_44418_cov_21.0; ` was written but the nucleotide sequence of this edge is missing.

I think that line 56 should be revised as following like line 48,
`o.write('>'+name+"_len_"+str(fields[0])+"_cov_"+str(fields[1])+";\n"+fields[2]+'\n')`

After runnning by the revised script, the error does not occur.
Do you think the revision is appropriate to run SCAPP using the fastg file converted from gfa format?

Additionaly, I'm wondering line 59 `elif len(pos_neighbours) > 0:` is correct. `else:` is correct, I suppose.

Why is it necessary to process `elif len(pos_neighbours) > 0: `even though `len(pos_neighbours) `have already been checked in line 53-56? 

Thank you.

**Comment by dpellow** [comment]
I guess that you are right about both, this has not really been adequately tested as SCAPP is really designed for short read assemblies. If you try it with long-reads let us know how it works out!

**Comment by brambloemen** [comment]
@yusuketsuda 
I'm testing the tool as well on a metaFlye generated assembly, and was getting the same error.

Thank you for providing this solution!

I encountered some additional issues, based on your feedback I modified lines 53-56, which look like this in the working version of the script:

```
if len(pos_neighbours) > 0:
	o.write('>'+name+"_len_"+str(fields[0])+"_cov_"+str(fields[1])+":"+",".join([n[1]+"_len_"+str(seqs_dict[n[1]][0])+"_cov_"+str(seqs_dict[n[1]][1])+("'"if n[2]=="-" else "") for n in pos_neighbours])+ ";\n"+fields[2]+'\n')
else:
	o.write('>'+name+"_len_"+str(fields[0])+"_cov_"+str(fields[1])+";\n"+fields[2]+'\n')
if len(neg_neighbours) > 0:
	o.write('>'+name+"_len_"+str(fields[0])+"_cov_"+str(fields[1])+"':"+",".join([n[1]+"_len_"+str(seqs_dict[n[1]][0])+"_cov_"+str(seqs_dict[n[1]][1])+("'"if n[2]=="-" else "") for n in neg_neighbours])+ ";\n"+rc(fields[2])+'\n')
else:
	o.write('>'+name+"_len_"+str(fields[0])+"_cov_"+str(fields[1])+"';\n"+rc(fields[2])+'\n')
```
