### ISSUE TITLE
k-mer selection

### ISSUE THREAD

**Issue by yuqing-feng** [Shamir-Lab/SCAPP#31]
Hi,
I have assembled some metagenomic sequencing data using megahit (v1.2.9) and the k-mer ranged from 21 to 141. Which graph file is suggested use? The larger the better (k=141)?

**Comment by dpellow** [comment]
Yes, it should be the maximum k. Note that megahit has a script to convert these contigs to fastg. I would typically run it like this in a pipeline with reads -> megahit -> scapp:
```
            intermediates = glob.glob(os.path.join(megahit_dir,"intermediate_contigs/*final.contigs.fa"))
            kmax = max([int(os.path.basename(f).split(".")[0].split("k")[1]) for f in intermediates])
            contigs_file = os.path.join(megahit_dir,"intermediate_contigs/k{}.contigs.fa".format(kmax))
            fastg = os.path.join(sample_dir,"assembly_graph_{}.fastg".format(kmax))
            cmd = "megahit_toolkit contig2fastg {} {} > {}".format(kmax,contigs_file,fastg)
```
