### ISSUE TITLE
is the program running normal?

### ISSUE THREAD

**Issue by Wanli-HE** [Shamir-Lab/SCAPP#36]
hi!

here is the scapp.log file;
(base) [wanlhe@g-12-l0002 logs]$ tail -200 scapp.log
04/05/2023 09:01: Beginning SCAPP workflow
04/05/2023 09:01: Got parameters:
        Input graph: assembly_res/ERR4334192_assembly_out/assembly_graph.fastg
        Output directory: circular/ERR4334192_k121__scapp_out
        Maximum k value: 121
        # processes: 40
        Maximum CV: 0.5
        Minimum Length: 1000
        Bamfile: None
        Reads file 1: qc_res/ERR4334192_1_kneaddata_paired_1.fastq.gz
        Reads file 2: qc_res/ERR4334192_1_kneaddata_paired_2.fastq.gz
        Use scores: True
        Use genes: True
        Path to BWA executables:
        Path to NCBI executables:
        Path to samtools executables:
        PlasClass scores file: None
04/05/2023 09:01: Creating fasta from fastg
04/05/2023 09:01: Creating BAM file
04/05/2023 09:01: Executing command: 'bwa index circular/ERR4334192_k121__scapp_out/intermediate_files/assembly_graph.nodes.fasta'
04/05/2023 09:07: Executing command: 'bwa mem -t 40 circular/ERR4334192_k121__scapp_out/intermediate_files/assembly_graph.nodes.fasta qc_res/ERR4334192_1_kneaddata_paired_1.fastq.gz qc_res/ERR4334192_1_kneaddata_paired_2.fastq.gz | samtools  view -buS -@ 39 - > circular/ERR4334192_k121__scapp_out/intermediate_files/reads_pe.bam'
04/05/2023 09:08: Executing command: 'samtools view -bF 0x0900 -@ 39 circular/ERR4334192_k121__scapp_out/intermediate_files/reads_pe.bam > circular/ERR4334192_k121__scapp_out/intermediate_files/reads_pe_primary.bam'
04/05/2023 09:08: Executing command: 'samtools sort circular/ERR4334192_k121__scapp_out/intermediate_files/reads_pe_primary.bam -o circular/ERR4334192_k121__scapp_out/intermediate_files/reads_pe_primary.sort.bam'
04/05/2023 09:08: Executing command: 'samtools index circular/ERR4334192_k121__scapp_out/intermediate_files/reads_pe_primary.sort.bam'
04/05/2023 09:08: 399.2395465373993 seconds to create indexed sorted bam file
04/05/2023 09:08: Using PlasClass to obtain sequence scores

it is showing runing plasclass, but when i check the plasclass log file show below, 
Loading classifier 1000
/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Loading classifier 10000
Loading classifier 100000
Loading classifier 500000
50000 sequences to classify. Classifying in batches of 100k
Starting new batch
Getting kmer frequencies for partition length 1000
Classifying sequences of length scale 1000
Getting kmer frequencies for partition length 10000
Classifying sequences of length scale 10000
Getting kmer frequencies for partition length 100000
Classifying sequences of length scale 100000
50000 sequences to classify. Classifying in batches of 100k
Starting new batch
Getting kmer frequencies for partition length 1000
Classifying sequences of length scale 1000

it is running for four days, using 40 cores, but still in this step, is that normal? as i know it is necessary need such long time for plasclass.

**Comment by dpellow** [comment]
No, running PlasClass should be a relatively fast step. Is what you copied the entire plasclass log file? Is it showing that it's using all 40 cores? (ie what is the CPU usage?)

**Comment by Wanli-HE** [comment]
> Is what you copied the entire plasclass log file? Is it showing that it's using all 40 cores? (ie what is the CPU usage?)

yes, i copy from the PlasClass log file.

here is all information for plasclass:
Loading classifier 1000
/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Loading classifier 10000
Loading classifier 100000
Loading classifier 500000
50000 sequences to classify. Classifying in batches of 100k
Starting new batch
Getting kmer frequencies for partition length 1000
Classifying sequences of length scale 1000
Getting kmer frequencies for partition length 10000
Classifying sequences of length scale 10000
50000 sequences to classify. Classifying in batches of 100k
Starting new batch
Getting kmer frequencies for partition length 1000
Classifying sequences of length scale 1000

and the common line is "scapp -g SRR3132475_assembly_out/assembly_graph.fastg -o circular/SRR3132475_k77__scapp_out -k 77 -r1 SRR3132475_1_reorder_1.fastq.gz -r2 SRR3132475_1_reorder_2.fastq.gz -p 40"

**Comment by dpellow** [comment]
It doesn't seem correct - it looks like plasclass stopped running if that's all that is in the log file. PlasClass should not take very long to run.
What is the current cpu usage if it is still running? For example the output of `top` or `htop`

**Comment by Wanli-HE** [comment]
> It doesn't seem correct - it looks like plasclass stopped running if that's all that is in the log file. PlasClass should not take very long to run. What is the current cpu usage if it is still running? For example the output of `top` or `htop`

i am running it in the cluster, i give 40 cores, but it seems like not running, but the use-time is still calculating, i will try to write e-mail to cluster to see what is going on

**Comment by dpellow** [comment]
ok, can you find out if it is still running, what the CPU usage is, and what command is currently executing?

**Comment by Wanli-HE** [comment]
> 
all the program is stoped, 

Creating BAM file of read mappings with BWA

Getting scores of graph nodes

Creating BAM file of read mappings with BWA

Getting scores of graph nodes

which means should be stoped in plasclass steps.

**Comment by dpellow** [comment]
ok I don't know why it stopped. Maybe just run it again? You can use the intermediate files such as the bam file in order to skip some of the initial steps.

**Comment by Wanli-HE** [comment]
> ok I don't know why it stopped. Maybe just run it again? You can use the intermediate files such as the bam file in order to skip some of the initial steps.

and other question, before running this i using k 77, but to requced time, i re-assembly with k 121, for now, can i still using k 77 to run?

**Comment by Wanli-HE** [comment]
> 

did you know this? here is the e-mail they answer me

The blocking with futex can be a bug.
Have you tried to contact the developers?

**Comment by dpellow** [comment]
> and other question, before running this i using k 77, but to requced time, i re-assembly with k 121, for now, can i still using k 77 to run?

It's not clear what you mean. You need to use the k that was used to create your assembly graph.

**Comment by dpellow** [comment]
> > 
> 
> did you know this? here is the e-mail they answer me
> 
> The blocking with futex can be a bug. Have you tried to contact the developers?


I don't have a good way to know what went wrong when running it on your cluster. Did they tell you what running state it was in? Was it really running for 4 days, with what CPU usage?
I don't think it should need 40 cores if that is the problem, you could try `-p 12` or lower if you think that is an issue

**Comment by Wanli-HE** [comment]
> 
so in the very beginning, i assembly using k=77, and i run scapp, because some samples running very long time, so i re-assembly using k=121, running scapp again, but now, i want to run k=77, because it is better all the samples using same parameter, so can i still using the k=121 graph to run scapp with k =77, or i should re-assembly  again using k=77 and then ru nning scapp

**Comment by Wanli-HE** [comment]
> I don't have a good way to know what went wrong when running it on your cluster. Did they tell you what running state it was in? Was it really running for 4 days, with what CPU usage?
> I don't think it should need 40 cores if that is the problem, you could try `-p 12` or lower if you think that is an issue

i check all the samples that are not successfully for runing scapp, all are stop in plasclass step, so may be some problems for the scapp when running in the claster,  i will try with low -p.

**Comment by dpellow** [comment]
> so in the very beginning, i assembly using k=77, and i run scapp, because some samples running very long time, so i re-assembly using k=121, running scapp again, but now, i want to run k=77, because it is better all the samples using same parameter, so can i still using the k=121 graph to run scapp with k =77, or i should re-assembly again using k=77 and then ru nning scapp

scapp needs to use the same value of k as your assembly, so if you want to use k=77 then both the assembly and scapp should use this. If you want to run all your samples using the same parameter you should assemble them the same way anyway. The assembly for k=121 and k=77 will be very different, it doesn't make to do some with one and some with the other, regardless of scapp...

**Comment by dpellow** [comment]
> > I don't have a good way to know what went wrong when running it on your cluster. Did they tell you what running state it was in? Was it really running for 4 days, with what CPU usage?
> > I don't think it should need 40 cores if that is the problem, you could try `-p 12` or lower if you think that is an issue
> 
> i check all the samples that are not successfully for runing scapp, all are stop in plasclass step, so may be some problems for the scapp when running in the claster, i will try with low -p.

I see. How many samples didn't run successfully? Out of how many?

**Comment by Wanli-HE** [comment]
> it doesn't make to do some with one and some with the other, regardless of scapp

total 9000 samples. only around  5200 were successful

**Comment by dpellow** [comment]
> total 9000 samples. only around 5200 were successful

This doesn't sound good. I have not seen similar problems with plasclass before. Let me know if reducing the amount of threads used by plasclass solves the issue.

**Comment by Wanli-HE** [comment]
> 
BTW I notice this on your current job.

UID        PID  PPID  C STIME TTY          TIME CMD

wanlhe   30919 39278  0 12:03 ?        00:00:00 -bash

wanlhe   31141 30919  0 12:03 ?        00:00:00  \_ /bin/sh /var/spool/torque/mom_priv/jobs/42517601.SC

wanlhe   31146 31141 84 12:03 ?        01:33:18      \_ /home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/bin/python3.7 /home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be

wanlhe     803 31146  0 12:25 ?        00:00:00          \_ [scapp] <defunct>

wanlhe     806 31146  0 12:25 ?        00:00:00          \_ [scapp] <defunct>

wanlhe     809 31146  0 12:25 ?        00:00:00          \_ [scapp] <defunct>

wanlhe     811 31146  0 12:25 ?        00:00:00          \_ [scapp] <defunct>

 

![image](https://user-images.githubusercontent.com/58076352/236819111-515080eb-5749-417e-9d42-7422960524d1.png)

**Comment by Wanli-HE** [comment]
> > total 9000 samples. only around 5200 were successful
> 
> This doesn't sound good. I have not seen similar problems with plasclass before. Let me know if reducing the amount of threads used by plasclass solves the issue.

here is the new testing results, it seems like the process have some problems

**Comment by Wanli-HE** [comment]
> > total 9000 samples. only around 5200 were successful
> 
> This doesn't sound good. I have not seen similar problems with plasclass before. Let me know if reducing the amount of threads used by plasclass solves the issue.

hi again!

i testing with -p 10, but it seems stop iin some step of plasclass.

Loading classifier 1000
/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Loading classifier 10000
Loading classifier 100000
Loading classifier 500000
50000 sequences to classify. Classifying in batches of 100k
Starting new batch
Getting kmer frequencies for partition length 1000
Classifying sequences of length scale 1000

here is the results!

**Comment by Wanli-HE** [comment]
> > > total 9000 samples. only around 5200 were successful
> > 
> > 
> > This doesn't sound good. I have not seen similar problems with plasclass before. Let me know if reducing the amount of threads used by plasclass solves the issue.
> 
> hi again!
> 
> i testing with -p 10, but it seems stop iin some step of plasclass.
> 
> Loading classifier 1000 /home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) /home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) Loading classifier 10000 Loading classifier 100000 Loading classifier 500000 50000 sequences to classify. Classifying in batches of 100k Starting new batch Getting kmer frequencies for partition length 1000 Classifying sequences of length scale 1000
> 
> here is the results!

may be i should try to run plasclass and plasflow individually, apart from scapp. one questions, and what is the input file for plasclass and plasflow, is the assemble contigs.fasta, or assembly_graph.fastg from spades?

**Comment by dpellow** [comment]
I don't know why it isn't working on your server, are you running it in a conda environment with scapp installed using conda? Maybe see if it can run on a different computer to check whether it is an issue with the running environment? I can try it locally if you want also.

> may be i should try to run plasclass and plasflow individually, apart from scapp. one questions, and what is the input file for plasclass and plasflow, is the assemble contigs.fasta, or assembly_graph.fastg from spades?

Yes I guess you could run plasclass separately and pass it as an input using the `-pc <filename>` option to scapp. It should be on the assembly graph that you will use to run scapp.

**Comment by Wanli-HE** [comment]
> 

hi， i found the problem, why my program is stop, due to plasclass, 

/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/projects/ku_00041/archive/plasclass/PlasClass/plasclass/plasclass_utils.py", line 132, in count_kmers
    shared_list[ret_ind] = kmer_freqs
  File "<string>", line 2, in __setitem__
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/projects/ku_00041/archive/plasclass/PlasClass/classify_fasta.py", line 82, in <module>
    main(args)
  File "/home/projects/ku_00041/archive/plasclass/PlasClass/classify_fasta.py", line 61, in main
    probs = c.classify(seqs)
  File "/home/projects/ku_00041/archive/plasclass/PlasClass/plasclass/plasclass.py", line 60, in classify
    pool.map(utils.count_kmers, [[ind, s, self._ks, self._kmer_inds, self._kmer_count_lens, shared_list] for ind,s in enumerate(part_seqs)])
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by Wanli-HE** [comment]
> > 
> 
> hi， i found the problem, why my program is stop, due to plasclass,
> 
> /home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) /home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 121, in worker result = (True, func(*args, **kwds)) File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar return list(map(*args)) File "/home/projects/ku_00041/archive/plasclass/PlasClass/plasclass/plasclass_utils.py", line 132, in count_kmers shared_list[ret_ind] = kmer_freqs File "", line 2, in **setitem** File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod kind, result = conn.recv() File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/connection.py", line 250, in recv buf = self._recv_bytes() File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes buf = self._recv(4) File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/connection.py", line 379, in _recv chunk = read(handle, remaining) ConnectionResetError: [Errno 104] Connection reset by peer """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/projects/ku_00041/archive/plasclass/PlasClass/classify_fasta.py", line 82, in main(args) File "/home/projects/ku_00041/archive/plasclass/PlasClass/classify_fasta.py", line 61, in main probs = c.classify(seqs) File "/home/projects/ku_00041/archive/plasclass/PlasClass/plasclass/plasclass.py", line 60, in classify pool.map(utils.count_kmers, [[ind, s, self._ks, self._kmer_inds, self._kmer_count_lens, shared_list] for ind,s in enumerate(part_seqs)]) File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 268, in map return self._map_async(func, iterable, mapstar, chunksize).get() File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/multiprocessing/pool.py", line 657, in get raise self._value ConnectionResetError: [Errno 104] Connection reset by peer

here is the error when i run plasclass individually,  

and other problem is that if you input "-p 10" it will raise another error, so i see the orgin code, maybe when pass parameters have some problems, but i am testing it

**Comment by dpellow** [comment]
> here is the error when i run plasclass individually,
>
>and other problem is that if you input "-p 10" it will raise another error, so i see the orgin code, maybe when pass parameters have some problems, but i am testing it

Can you please report the command that you used. What is the error with using `-p 10`?

Also, what happens if you use only 1 thread?

**Comment by Wanli-HE** [comment]
> > here is the error when i run plasclass individually,
> > and other problem is that if you input "-p 10" it will raise another error, so i see the orgin code, maybe when pass parameters have some problems, but i am testing it
> 
> Can you please report the command that you used. What is the error with using `-p 10`?
> 
> Also, what happens if you use only 1 thread?

hi! i tried with running plasclass indivivually, but it not works, so i just decided jump plasclass using other tool to predict each graph,
