### ISSUE TITLE
the origin code

### ISSUE THREAD

**Issue by Wanli-HE** [Shamir-Lab/SCAPP#37]
Hi again!

i see the origin code and find some parts could discuss with.

first,  In the step 6:  "#Step 6: Post-process filtering: Classify gene filtered plasmids ;  **if use_scores:** "  in this step you just run plasclass for assembled circular contigs, but you flag in here is judging whether using use_scores for graph nodes,  here are two things right? maybe in here you should make another flag like use_scores, and use can provides the file by themself.

second, in the last step,  "# Step 7: Create set of confident plasmid predictions: # Confident plasmid predictions - 2 out of 3 of: gene hits, plasmid classification, self loops; **if use_scores and use_genes:**", if one of the flag is false, you can get the final file.

another thing is the flag of use_scores and  use_genes are both false, what is the different with recycler? is that will be recycler.

best,
wanli

**Comment by dpellow** [comment]
Thanks for the suggestions.

No there are other differences from the Recycler algorithm.
