### ISSUE TITLE
SCAPP don't find plasmid in Cami1 dataset

### ISSUE THREAD

**Issue by SilasK** [Shamir-Lab/SCAPP#7]
The cami 1 dataset, should contain plasmids.

I assembled it with metaspades (up to K99) and run SCPP:
It didn't produce the main output file:

The log ends with: 
```
24/01/2020 17:30: Num path tuples: 0
24/01/2020 17:30: 85.27987575531006 seconds to run SCAPP plasmid finding
24/01/2020 17:30: Filtering plasmids by plasmid-specific genes
24/01/2020 17:30: 26.562718391418457 seconds to filter plasmids using plasmid-specific gene hits
24/01/2020 17:30: Using PlasClass to obtain scores of cycles
24/01/2020 17:30: Transforming scores
24/01/2020 17:30: 4.047647476196289 seconds to filter cycles by PlasClass score
24/01/2020 17:30: 0.03145933151245117 seconds to filter confident plasmids
```
[scap_logs.tar.gz](https://github.com/Shamir-Lab/SCAPP/files/4113205/scap_logs.tar.gz)

I think this means scapp didn't found any plasmids, right? 
Is the CAMI1 dataset too complicated for SCAPP to handle?

**Comment by dpellow** [comment]
@SilasK Thanks for notifying us about this, SCAPP should produce the main output file even if there are no plasmids (it will just be empty) so I think there is something else going wrong that I would like to debug.
Thanks for attaching the logs - it is helpful. Could you also check the files in the intermediate files directory and let me know what files are there. Also - how many plasmids are in each of the *.fasta files in the intermediate files.

**Comment by SilasK** [comment]
I found the main output file, sorry.

**Comment by dpellow** [comment]
@SilasK glad to hear that it worked!

Good to hear about results on the Cami dataset as well. Do you know what precision and recall that gives?

**Comment by SilasK** [comment]
I don’t have intended to do a proper assessment but I could do it but not this week.
