### ISSUE TITLE
warning incompatible versions

### ISSUE THREAD

**Issue by SilasK** [Shamir-Lab/SCAPP#8]
Did I already mention this? 

/home/kiesers/scratch/miniconda3/envs/scapp/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk

**Comment by dpellow** [comment]
Thanks!
Yes, it's coming from PlasClass - which was originally in Python2 and then ported to Python3. The models were trained and saved in a Python2 compatible version. I tested the Python2 and Python3 versions of PlasClass and had no problems or differences between the two.
