### ISSUE TITLE
Process seems stuck at 'Transforming scores' stage when using GeneHits info

### ISSUE THREAD

**Issue by jnesme** [Shamir-Lab/SCAPP#9]
Hi David - finally having time to run tests on SCAPP.

I've been running on the same graph SCAPP with or without information from gene hits.  I'm working on a SGE cluster and while jobs using only PlasClass scores seems to behave properly, when I try to use plasmid specific gene hits information, the process is stuck at the "Transforming scores" stage (been running for 60H on 28 CPUs now). Please find the tail of scapp.log below:

18097D-03-78/SCAPPwGeneHits_out/logs/scapp.log
`
05/03/2020 01:06:       CV: 0.503121
05/03/2020 01:06: Remaining nodes: 203932
05/03/2020 01:06: Getting edge weights
05/03/2020 01:06: Getting shortest paths
05/03/2020 01:14: 81971.08901453018 seconds to run SCAPP plasmid finding
05/03/2020 01:14: Using PlasClass to obtain scores of cycles
05/03/2020 01:14: Transforming scores
`

18097D-03-78/SCAPP_out/logs/scapp.log (no plasmid specific gene hits)
`
03/03/2020 09:20:       CV: 0.503121
03/03/2020 09:20: Remaining nodes: 203932
03/03/2020 09:20: Getting edge weights
03/03/2020 09:20: Getting shortest paths
03/03/2020 09:32: 108940.01605129242 seconds to run SCAPP plasmid finding
03/03/2020 09:32: Filtering plasmids by plasmid-specific genes
03/03/2020 09:32: 35.37972712516785 seconds to filter plasmids using plasmid-specific gene hits
03/03/2020 09:32: Using PlasClass to obtain scores of cycles
03/03/2020 09:32: Transforming scores
03/03/2020 09:32: 6.1761133670806885 seconds to filter cycles by PlasClass score
03/03/2020 09:32: 0.014404058456420898 seconds to filter confident plasmids
`

I've installed SCAPP in a conda environment but probably because of channel priority ended up with samtools version 1.7 - Is that a likely explanation ?

**Comment by dpellow** [comment]
Hi Joseph, thanks for letting us know about this issue.
What is the command that you are using in each case?
It's possible that the samtools version in causing the problem - is it possible to test with an updated version? Feel free to email me the full log files (all the files in the 'logs' directory in both cases) at dpellow@post.tau.ac.il and I can try to help further.

**Comment by dpellow** [comment]
@jnesme were you able to confirm that the program did not complete running? Have you tried with newer versions of SCAPP?
I am closing the issue, feel free to re-open if it doesn't look solved on your end.
